TaskMangement/Controllers/TasksController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskMangement.Constants;
using TaskMangement.Data;
using TaskMangement.Models;
using TaskMangement.ViewModels;

namespace TaskMangement.Controllers
{
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<SystemUser> _userManager;
        
        public TasksController(ApplicationDbContext context, UserManager<SystemUser> userManager)
        {

            _context = context;
            _userManager= userManager;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser =await _userManager.GetUserAsync(User);

            if (currentUser != null)
            {
            var Tasks = _context.doLists.Include(r=>r.systemUser).Where(d=>d.systemUser.Id==currentUser.Id).ToList();

            return View(Tasks);
            }
            return View(new List<DoList>());
            
        }
        public async Task<IActionResult> Add()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var model = new TaskViewModel() { UserId = user.Id };
                return View(model);
            }
            else
            {
                return View(new TaskViewModel());
            }



        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(TaskViewModel model)
        {
            var user =await _userManager.GetUserAsync(User);
            
            if (!ModelState.IsValid)
                return View(model);

            
            if(model.dueDate <= DateTime.Now)
            {
                ModelState.Clear();
                ModelState.AddModelError("dueDate", "Invalid Task Time Make it bigger from now");
                return View(model);
            }
            if(model.Title==string.Empty)
            {
                ModelState.Clear();
                ModelState.AddModelError("Title", "Title Required");
                return View(model);
            }
            
           
            if (model.UserId ==null)
            {
                ModelState.AddModelError("UserId", "You have to sign in to add tasks");
                return View(model);
            }
            var result = new DoList
            {
                Title = model.Title,
                Description = model.Description,
                dueDate = model.dueDate,
                status = $"{StatusConsts.notStarted}",
                systemUser = user,
                

            };
            _context.Add(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));


        }

        public async Task<IActionResult> edit(int id)
        {
            var Task = _context.doLists.Find(id);
            if (Task == null)
                return NotFound();
            var result = new TaskViewModel
            {
                ID = Task.ID,
                Title = Task.Title,
                Description = Task.Description,
                status = Task.status,
                dueDate = Task.dueDate
            };
            return View("Add", result);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> edit(TaskViewModel model)
        {
            var task = _context.doLists.Find(model.ID);

            if (!ModelState.IsValid)
                return View("add",model);


            if (model.dueDate <= DateTime.Now)
            {
                ModelState.Clear();
                ModelState.AddModelError("dueDate", "Invalid Task Time Make it bigger from now");
                return View("add", model);
            }
            if (model.Title == string.Empty)
            {
                ModelState.Clear();
                ModelState.AddModelError("Title", "Title Required");
                return View("add", model);
            }
            task.Title = model.Title;
            task.Description=model.Description;
            task.status = model.status;
            task.dueDate = model.dueDate;
            

            _context.Update(task);
           
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));


        }
        public async Task<IActionResult> details(int id)
        {
            var task =await _context.doLists.FindAsync(id);
            if (task == null)
                return NotFound();

            return View(task);

        }
        public async Task<IActionResult> Delete(int id)
        {
            var task = _context.doLists.Find(id);
            if (task == null) return NotFound();

            _context.Remove(task);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

  
    }

}

TaskMangement/Controllers/authController.cs
using Azure.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TaskMangement.Models;
using TaskMangement.ViewModels;

namespace TaskMangement.Controllers
{
    public class authController : Controller
    {
        private readonly UserManager<SystemUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<SystemUser> _signIn;
        public authController(RoleManager<IdentityRole> roleManager, UserManager<SystemUser> userManager, SignInManager<SystemUser> signIn)
        {
            _roleManager = roleManager;
            _userManager = userManager;

            _signIn = signIn;

        }
        public IActionResult Index()
        {
            return View();
        }

       public async Task<IActionResult> login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> login(loginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signIn.PasswordSignInAsync(model.Email
                    , model.password, isPersistent: false
                    , lockoutOnFailure: false);
                if (result.Succeeded)
                {

                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "Invalid Cradintails");
            }
                return View(model);
            
        }

        public IActionResult signUp()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> signUp(SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new SystemUser
                {
                    Email = model.Email,
                    UserName = model.Email
                };
              var result= await _userManager.CreateAsync(user,model.Password);
                
                if (!result.Succeeded)
                    
                {
                    foreach(var error in result.Errors)
                    {


                    ModelState.AddModelError("", error.Description);
                        
                    }
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return View(model);
        }
        public async Task<IActionResult> SignOut()
        {
            await _signIn.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

TaskMangement/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskMangement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	
    <link rel="stylesheet" href="~/TaskMangement.styles.css" asp-append-version="true" />
</head>
<body>
    @{
        var userName = User.Identity.IsAuthenticated ? User.Identity.Name : "Guest";
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskMangement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a>
                        </li>
                        <li class="navbar-text flex-grow-1"></li>
                        <span class="navbar-text">
                            Welcome, @userName
                        </span>
                        @if (!userName.Equals("Guest"))
                        {
                            <li class="nav-item  " style="justify-content:end">
                                <a class="nav-link text-danger" asp-area="" asp-controller="auth" asp-action="SignOut">SignOut</a>
                            </li>
                        }
                        <li class="nav-item  " style="justify-content:end">
                            <a class="nav-link text-dark" asp-area="" asp-controller="auth" asp-action="Login">login</a>
                        </li>
                        <li class="nav-item  " style="">
                            <a class="nav-link text-dark" asp-area="" asp-controller="auth" asp-action="signup">SignUp</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaskMangement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>